"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# This is CORS and XFRAME configuration to allow cross-site requests
CORS_ORIGIN_ALLOW_ALL = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# This contains the list of allowed hosts
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cachalot',
]


# Cachalot configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_FINDER = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),

]

TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)

# These settings are used for settings setting up an email service by connecting to an SMTP server.
# Please, configure accordingly.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.example_host.com'
EMAIL_PORT = 587
EMAIL_PROTOCOL = 'smtp'
EMAIL_HOST_USER = 'noreply@epu.ntua.gr'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'noreply@epu.ntua.gr'
EMAIL_FROM = 'noreply@epu.ntua.gr'
SERVER_EMAIL = 'noreply@epu.ntua.gr'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")


# This is the site key of the Google captcha if needed on the website.
# Create a new pair of catch keys here: https://cloud.google.com/recaptcha-enterprise/docs/create-key
# Configure accordingly.
GOOGLE_RECAPTCHA_SITE_KEY = '6LewHqEdAAAAAG7A1uY2PJJbdLksCuhlD_N4k49j'



# PRIVATE SETTINGS
# If you use docker for these values are retrieved from the environment variables of the application
# If not, the default values provided are used.

# APP SETTINGS
SECRET_KEY = os.environ.get("SECRET_KEY", "test_key")
DEBUG = int(os.environ.get("DEBUG", default=1))

# CAPTCHA SETTINGS
GOOGLE_RECAPTCHA_SECRET_KEY = os.environ.get("GOOGLE_RECAPTCHA_SECRET_KEY")

# EMAIL - SMTP SETTINGS
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

#DATABASE SETTINGS
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("SQL_DATABASE", 'db_name'),
        'USER': os.environ.get("SQL_USER", 'db_user'),
        'PASSWORD': os.environ.get("SQL_PASSWORD", 'db_pass'),
        "HOST": os.environ.get("SQL_HOST", 'db_host'),
        "PORT": os.environ.get("SQL_PORT", '5435'),
    }
}